import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import SetupWizardView from '@/views/setup/SetupWizardView.vue'

const { testDatabaseMock, testRedisMock, installMock } = vi.hoisted(() => ({
  testDatabaseMock: vi.fn(),
  testRedisMock: vi.fn(),
  installMock: vi.fn()
}))

vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/api/setup', () => ({
  testDatabase: testDatabaseMock,
  testRedis: testRedisMock,
  install: installMock
}))
vi.mock('@/api/client', () => ({ buildGatewayUrl: (path: string) => path }))

function button(wrapper: VueWrapper, key: string) {
  const match = wrapper.findAll('button').find((item) => item.text() === key)
  expect(match, `Missing button ${key}`).toBeDefined()
  return match!
}

async function mountAdminStep() {
  const wrapper = mount(SetupWizardView, {
    global: { stubs: { Icon: true, Select: true, Toggle: true } }
  })
  for (let step = 0; step < 2; step++) {
    expect(button(wrapper, 'common.next').attributes('disabled')).toBeDefined()
    await button(wrapper, 'setup.status.testConnection').trigger('click')
    await flushPromises()
    await button(wrapper, 'common.next').trigger('click')
  }
  expect(testDatabaseMock).toHaveBeenCalledOnce()
  expect(testRedisMock).toHaveBeenCalledOnce()
  return wrapper
}

async function fillAdmin(wrapper: VueWrapper, email: string, password: string, confirmation = password) {
  await wrapper.get('input[type="email"]').setValue(email)
  const inputs = wrapper.findAll('input[type="password"]')
  await inputs[0].setValue(password)
  await inputs[1].setValue(confirmation)
}

beforeEach(() => {
  vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] })
  vi.clearAllMocks()
  testDatabaseMock.mockResolvedValue(undefined)
  testRedisMock.mockResolvedValue(undefined)
  installMock.mockResolvedValue({ message: 'ok', restart: true })
})
afterEach(() => {
  vi.clearAllTimers()
  vi.useRealTimers()
})

describe('Setup wizard optional administrator credentials', () => {
  it.each([
    ['', ''],
    ['owner@example.com', ''],
    ['', 'ValidPassword123']
  ])('allows separate defaults and submits unchanged email=%s password=%s', async (email, password) => {
    const wrapper = await mountAdminStep()
    expect(wrapper.text()).toContain('setup.admin.generatedCredentialsHint')
    await fillAdmin(wrapper, email, password)
    expect(wrapper.text()).toContain('setup.admin.generatedCredentialsHint')
    expect(button(wrapper, 'common.next').attributes('disabled')).toBeUndefined()
    await button(wrapper, 'common.next').trigger('click')
    expect(wrapper.text()).toContain(email || 'setup.admin.autoGenerated')
    expect(wrapper.text()).toContain('setup.admin.generatedCredentialsHint')
    await button(wrapper, 'setup.status.completeInstallation').trigger('click')
    await flushPromises()
    expect(installMock).toHaveBeenCalledOnce()
    expect(installMock.mock.calls[0][0].admin).toEqual({ email, password })
    expect(wrapper.text()).toContain('setup.status.completed')
    wrapper.unmount()
  })

  it.each(['  ', '        '])('treats whitespace-only password %j as a default without confirmation', async (password) => {
    const wrapper = await mountAdminStep()
    await fillAdmin(wrapper, 'owner@example.com', 'ValidPassword123', 'different')
    await wrapper.get('#admin-password').setValue(password)
    expect(wrapper.get('#admin-password').attributes('aria-invalid')).toBe('false')
    expect(wrapper.get('#admin-confirm-password').attributes('disabled')).toBeDefined()
    expect(wrapper.text()).not.toContain('setup.admin.passwordMismatch')
    expect(wrapper.text()).toContain('setup.admin.generatedCredentialsHint')
    expect(button(wrapper, 'common.next').attributes('disabled')).toBeUndefined()
    await button(wrapper, 'common.next').trigger('click')
    expect(wrapper.text()).toContain('owner@example.com')
    expect(wrapper.text()).toContain('setup.admin.generatedCredentialsHint')
    await button(wrapper, 'setup.status.completeInstallation').trigger('click')
    await flushPromises()
    expect(installMock).toHaveBeenCalledOnce()
    expect(installMock.mock.calls[0][0].admin).toEqual({ email: 'owner@example.com', password })
    wrapper.unmount()
  })

  it.each(['a'.repeat(8), 'ValidPassword123', '  ValidPassword123  ', '界'.repeat(3), 'a'.repeat(72), '界'.repeat(24)])('preserves explicit valid credentials (%s)', async (password) => {
    const wrapper = await mountAdminStep()
    await fillAdmin(wrapper, 'owner@example.com', password)
    expect(button(wrapper, 'common.next').attributes('disabled')).toBeUndefined()
    await button(wrapper, 'common.next').trigger('click')
    expect(wrapper.text()).not.toContain('setup.admin.generatedCredentialsHint')
    await button(wrapper, 'setup.status.completeInstallation').trigger('click')
    await flushPromises()
    expect(installMock.mock.calls[0][0].admin).toEqual({ email: 'owner@example.com', password })
    wrapper.unmount()
  })

  it.each([
    ['not-an-email', 'ValidPassword123', 'ValidPassword123'],
    ['owner@example.com', 'short', 'short'],
    ['owner@example.com', '界界', '界界'],
    ['owner@example.com', 'a'.repeat(73), 'a'.repeat(73)],
    ['owner@example.com', '界'.repeat(25), '界'.repeat(25)],
    ['owner@example.com', 'ValidPassword123', 'different'],
    ['owner@example.com', 'ValidPassword123', '']
  ])('blocks invalid or mismatched explicit credentials (%s, %s)', async (email, password, confirmation) => {
    const wrapper = await mountAdminStep()
    await fillAdmin(wrapper, email, password, confirmation)
    expect(button(wrapper, 'common.next').attributes('disabled')).toBeDefined()
    await button(wrapper, 'common.next').trigger('click')
    expect(wrapper.findAll('input[type="email"]')).toHaveLength(1)
    expect(installMock).not.toHaveBeenCalled()
    wrapper.unmount()
  })

  it('does not require confirmation when password is cleared', async () => {
    const wrapper = await mountAdminStep()
    await fillAdmin(wrapper, '', 'ValidPassword123')
    await wrapper.get('#admin-password').setValue('')
    expect(wrapper.get('#admin-confirm-password').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'common.next').attributes('disabled')).toBeUndefined()
    expect(wrapper.text()).not.toContain('setup.admin.passwordMismatch')
    wrapper.unmount()
  })
})
