// Code generated by ent, DO NOT EDIT.

package usagelogdetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usagelogdetail type in the database.
	Label = "usage_log_detail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldRequestHeaders holds the string denoting the request_headers field in the database.
	FieldRequestHeaders = "request_headers"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldResponseHeaders holds the string denoting the response_headers field in the database.
	FieldResponseHeaders = "response_headers"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUsageLog holds the string denoting the usage_log edge name in mutations.
	EdgeUsageLog = "usage_log"
	// Table holds the table name of the usagelogdetail in the database.
	Table = "usage_log_details"
	// UsageLogTable is the table that holds the usage_log relation/edge.
	UsageLogTable = "usage_log_details"
	// UsageLogInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogInverseTable = "usage_logs"
	// UsageLogColumn is the table column denoting the usage_log relation/edge.
	UsageLogColumn = "usage_log_id"
)

// Columns holds all SQL columns for usagelogdetail fields.
var Columns = []string{
	FieldID,
	FieldUsageLogID,
	FieldRequestHeaders,
	FieldRequestBody,
	FieldResponseHeaders,
	FieldResponseBody,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestHeaders holds the default value on creation for the "request_headers" field.
	DefaultRequestHeaders string
	// DefaultRequestBody holds the default value on creation for the "request_body" field.
	DefaultRequestBody string
	// DefaultResponseHeaders holds the default value on creation for the "response_headers" field.
	DefaultResponseHeaders string
	// DefaultResponseBody holds the default value on creation for the "response_body" field.
	DefaultResponseBody string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageLogDetail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByRequestHeaders orders the results by the request_headers field.
func ByRequestHeaders(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHeaders, opts...).ToFunc()
}

// ByRequestBody orders the results by the request_body field.
func ByRequestBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBody, opts...).ToFunc()
}

// ByResponseHeaders orders the results by the response_headers field.
func ByResponseHeaders(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseHeaders, opts...).ToFunc()
}

// ByResponseBody orders the results by the response_body field.
func ByResponseBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBody, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUsageLogField orders the results by usage_log field.
func ByUsageLogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogStep(), sql.OrderByField(field, opts...))
	}
}
func newUsageLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
	)
}
