// Code generated by ent, DO NOT EDIT.

package usagelogdetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldID, id))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUsageLogID, v))
}

// RequestHeaders applies equality check predicate on the "request_headers" field. It's identical to RequestHeadersEQ.
func RequestHeaders(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestHeaders, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestBody, v))
}

// UpstreamRequestHeaders applies equality check predicate on the "upstream_request_headers" field. It's identical to UpstreamRequestHeadersEQ.
func UpstreamRequestHeaders(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestBody applies equality check predicate on the "upstream_request_body" field. It's identical to UpstreamRequestBodyEQ.
func UpstreamRequestBody(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpstreamRequestBody, v))
}

// ResponseHeaders applies equality check predicate on the "response_headers" field. It's identical to ResponseHeadersEQ.
func ResponseHeaders(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseHeaders, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseBody, v))
}

// UpstreamResponseHeaders applies equality check predicate on the "upstream_response_headers" field. It's identical to UpstreamResponseHeadersEQ.
func UpstreamResponseHeaders(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseBody applies equality check predicate on the "upstream_response_body" field. It's identical to UpstreamResponseBodyEQ.
func UpstreamResponseBody(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpstreamResponseBody, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// RequestHeadersEQ applies the EQ predicate on the "request_headers" field.
func RequestHeadersEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestHeaders, v))
}

// RequestHeadersNEQ applies the NEQ predicate on the "request_headers" field.
func RequestHeadersNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldRequestHeaders, v))
}

// RequestHeadersIn applies the In predicate on the "request_headers" field.
func RequestHeadersIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldRequestHeaders, vs...))
}

// RequestHeadersNotIn applies the NotIn predicate on the "request_headers" field.
func RequestHeadersNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldRequestHeaders, vs...))
}

// RequestHeadersGT applies the GT predicate on the "request_headers" field.
func RequestHeadersGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldRequestHeaders, v))
}

// RequestHeadersGTE applies the GTE predicate on the "request_headers" field.
func RequestHeadersGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldRequestHeaders, v))
}

// RequestHeadersLT applies the LT predicate on the "request_headers" field.
func RequestHeadersLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldRequestHeaders, v))
}

// RequestHeadersLTE applies the LTE predicate on the "request_headers" field.
func RequestHeadersLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldRequestHeaders, v))
}

// RequestHeadersContains applies the Contains predicate on the "request_headers" field.
func RequestHeadersContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldRequestHeaders, v))
}

// RequestHeadersHasPrefix applies the HasPrefix predicate on the "request_headers" field.
func RequestHeadersHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldRequestHeaders, v))
}

// RequestHeadersHasSuffix applies the HasSuffix predicate on the "request_headers" field.
func RequestHeadersHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldRequestHeaders, v))
}

// RequestHeadersEqualFold applies the EqualFold predicate on the "request_headers" field.
func RequestHeadersEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldRequestHeaders, v))
}

// RequestHeadersContainsFold applies the ContainsFold predicate on the "request_headers" field.
func RequestHeadersContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldRequestHeaders, v))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyContains applies the Contains predicate on the "request_body" field.
func RequestBodyContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldRequestBody, v))
}

// RequestBodyHasPrefix applies the HasPrefix predicate on the "request_body" field.
func RequestBodyHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldRequestBody, v))
}

// RequestBodyHasSuffix applies the HasSuffix predicate on the "request_body" field.
func RequestBodyHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldRequestBody, v))
}

// RequestBodyEqualFold applies the EqualFold predicate on the "request_body" field.
func RequestBodyEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldRequestBody, v))
}

// RequestBodyContainsFold applies the ContainsFold predicate on the "request_body" field.
func RequestBodyContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldRequestBody, v))
}

// UpstreamRequestHeadersEQ applies the EQ predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersNEQ applies the NEQ predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersIn applies the In predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldUpstreamRequestHeaders, vs...))
}

// UpstreamRequestHeadersNotIn applies the NotIn predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldUpstreamRequestHeaders, vs...))
}

// UpstreamRequestHeadersGT applies the GT predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersGTE applies the GTE predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersLT applies the LT predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersLTE applies the LTE predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersContains applies the Contains predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersHasPrefix applies the HasPrefix predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersHasSuffix applies the HasSuffix predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersEqualFold applies the EqualFold predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestHeadersContainsFold applies the ContainsFold predicate on the "upstream_request_headers" field.
func UpstreamRequestHeadersContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldUpstreamRequestHeaders, v))
}

// UpstreamRequestBodyEQ applies the EQ predicate on the "upstream_request_body" field.
func UpstreamRequestBodyEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyNEQ applies the NEQ predicate on the "upstream_request_body" field.
func UpstreamRequestBodyNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyIn applies the In predicate on the "upstream_request_body" field.
func UpstreamRequestBodyIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldUpstreamRequestBody, vs...))
}

// UpstreamRequestBodyNotIn applies the NotIn predicate on the "upstream_request_body" field.
func UpstreamRequestBodyNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldUpstreamRequestBody, vs...))
}

// UpstreamRequestBodyGT applies the GT predicate on the "upstream_request_body" field.
func UpstreamRequestBodyGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyGTE applies the GTE predicate on the "upstream_request_body" field.
func UpstreamRequestBodyGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyLT applies the LT predicate on the "upstream_request_body" field.
func UpstreamRequestBodyLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyLTE applies the LTE predicate on the "upstream_request_body" field.
func UpstreamRequestBodyLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyContains applies the Contains predicate on the "upstream_request_body" field.
func UpstreamRequestBodyContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyHasPrefix applies the HasPrefix predicate on the "upstream_request_body" field.
func UpstreamRequestBodyHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyHasSuffix applies the HasSuffix predicate on the "upstream_request_body" field.
func UpstreamRequestBodyHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyEqualFold applies the EqualFold predicate on the "upstream_request_body" field.
func UpstreamRequestBodyEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldUpstreamRequestBody, v))
}

// UpstreamRequestBodyContainsFold applies the ContainsFold predicate on the "upstream_request_body" field.
func UpstreamRequestBodyContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldUpstreamRequestBody, v))
}

// ResponseHeadersEQ applies the EQ predicate on the "response_headers" field.
func ResponseHeadersEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseHeaders, v))
}

// ResponseHeadersNEQ applies the NEQ predicate on the "response_headers" field.
func ResponseHeadersNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldResponseHeaders, v))
}

// ResponseHeadersIn applies the In predicate on the "response_headers" field.
func ResponseHeadersIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldResponseHeaders, vs...))
}

// ResponseHeadersNotIn applies the NotIn predicate on the "response_headers" field.
func ResponseHeadersNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldResponseHeaders, vs...))
}

// ResponseHeadersGT applies the GT predicate on the "response_headers" field.
func ResponseHeadersGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldResponseHeaders, v))
}

// ResponseHeadersGTE applies the GTE predicate on the "response_headers" field.
func ResponseHeadersGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldResponseHeaders, v))
}

// ResponseHeadersLT applies the LT predicate on the "response_headers" field.
func ResponseHeadersLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldResponseHeaders, v))
}

// ResponseHeadersLTE applies the LTE predicate on the "response_headers" field.
func ResponseHeadersLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldResponseHeaders, v))
}

// ResponseHeadersContains applies the Contains predicate on the "response_headers" field.
func ResponseHeadersContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldResponseHeaders, v))
}

// ResponseHeadersHasPrefix applies the HasPrefix predicate on the "response_headers" field.
func ResponseHeadersHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldResponseHeaders, v))
}

// ResponseHeadersHasSuffix applies the HasSuffix predicate on the "response_headers" field.
func ResponseHeadersHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldResponseHeaders, v))
}

// ResponseHeadersEqualFold applies the EqualFold predicate on the "response_headers" field.
func ResponseHeadersEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldResponseHeaders, v))
}

// ResponseHeadersContainsFold applies the ContainsFold predicate on the "response_headers" field.
func ResponseHeadersContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldResponseHeaders, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyContains applies the Contains predicate on the "response_body" field.
func ResponseBodyContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldResponseBody, v))
}

// ResponseBodyHasPrefix applies the HasPrefix predicate on the "response_body" field.
func ResponseBodyHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldResponseBody, v))
}

// ResponseBodyHasSuffix applies the HasSuffix predicate on the "response_body" field.
func ResponseBodyHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldResponseBody, v))
}

// ResponseBodyEqualFold applies the EqualFold predicate on the "response_body" field.
func ResponseBodyEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldResponseBody, v))
}

// ResponseBodyContainsFold applies the ContainsFold predicate on the "response_body" field.
func ResponseBodyContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldResponseBody, v))
}

// UpstreamResponseHeadersEQ applies the EQ predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersNEQ applies the NEQ predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersIn applies the In predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldUpstreamResponseHeaders, vs...))
}

// UpstreamResponseHeadersNotIn applies the NotIn predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldUpstreamResponseHeaders, vs...))
}

// UpstreamResponseHeadersGT applies the GT predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersGTE applies the GTE predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersLT applies the LT predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersLTE applies the LTE predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersContains applies the Contains predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersHasPrefix applies the HasPrefix predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersHasSuffix applies the HasSuffix predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersEqualFold applies the EqualFold predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseHeadersContainsFold applies the ContainsFold predicate on the "upstream_response_headers" field.
func UpstreamResponseHeadersContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldUpstreamResponseHeaders, v))
}

// UpstreamResponseBodyEQ applies the EQ predicate on the "upstream_response_body" field.
func UpstreamResponseBodyEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyNEQ applies the NEQ predicate on the "upstream_response_body" field.
func UpstreamResponseBodyNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyIn applies the In predicate on the "upstream_response_body" field.
func UpstreamResponseBodyIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldUpstreamResponseBody, vs...))
}

// UpstreamResponseBodyNotIn applies the NotIn predicate on the "upstream_response_body" field.
func UpstreamResponseBodyNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldUpstreamResponseBody, vs...))
}

// UpstreamResponseBodyGT applies the GT predicate on the "upstream_response_body" field.
func UpstreamResponseBodyGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyGTE applies the GTE predicate on the "upstream_response_body" field.
func UpstreamResponseBodyGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyLT applies the LT predicate on the "upstream_response_body" field.
func UpstreamResponseBodyLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyLTE applies the LTE predicate on the "upstream_response_body" field.
func UpstreamResponseBodyLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyContains applies the Contains predicate on the "upstream_response_body" field.
func UpstreamResponseBodyContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyHasPrefix applies the HasPrefix predicate on the "upstream_response_body" field.
func UpstreamResponseBodyHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyHasSuffix applies the HasSuffix predicate on the "upstream_response_body" field.
func UpstreamResponseBodyHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyEqualFold applies the EqualFold predicate on the "upstream_response_body" field.
func UpstreamResponseBodyEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldUpstreamResponseBody, v))
}

// UpstreamResponseBodyContainsFold applies the ContainsFold predicate on the "upstream_response_body" field.
func UpstreamResponseBodyContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldUpstreamResponseBody, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUsageLog applies the HasEdge predicate on the "usage_log" edge.
func HasUsageLog() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogWith applies the HasEdge predicate on the "usage_log" edge with a given conditions (other predicates).
func HasUsageLogWith(preds ...predicate.UsageLog) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(func(s *sql.Selector) {
		step := newUsageLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.NotPredicates(p))
}
