// Code generated by ent, DO NOT EDIT.

package usagelogdetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldID, id))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUsageLogID, v))
}

// RequestHeaders applies equality check predicate on the "request_headers" field. It's identical to RequestHeadersEQ.
func RequestHeaders(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestHeaders, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestBody, v))
}

// ResponseHeaders applies equality check predicate on the "response_headers" field. It's identical to ResponseHeadersEQ.
func ResponseHeaders(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseHeaders, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseBody, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// RequestHeadersEQ applies the EQ predicate on the "request_headers" field.
func RequestHeadersEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestHeaders, v))
}

// RequestHeadersNEQ applies the NEQ predicate on the "request_headers" field.
func RequestHeadersNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldRequestHeaders, v))
}

// RequestHeadersIn applies the In predicate on the "request_headers" field.
func RequestHeadersIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldRequestHeaders, vs...))
}

// RequestHeadersNotIn applies the NotIn predicate on the "request_headers" field.
func RequestHeadersNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldRequestHeaders, vs...))
}

// RequestHeadersGT applies the GT predicate on the "request_headers" field.
func RequestHeadersGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldRequestHeaders, v))
}

// RequestHeadersGTE applies the GTE predicate on the "request_headers" field.
func RequestHeadersGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldRequestHeaders, v))
}

// RequestHeadersLT applies the LT predicate on the "request_headers" field.
func RequestHeadersLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldRequestHeaders, v))
}

// RequestHeadersLTE applies the LTE predicate on the "request_headers" field.
func RequestHeadersLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldRequestHeaders, v))
}

// RequestHeadersContains applies the Contains predicate on the "request_headers" field.
func RequestHeadersContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldRequestHeaders, v))
}

// RequestHeadersHasPrefix applies the HasPrefix predicate on the "request_headers" field.
func RequestHeadersHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldRequestHeaders, v))
}

// RequestHeadersHasSuffix applies the HasSuffix predicate on the "request_headers" field.
func RequestHeadersHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldRequestHeaders, v))
}

// RequestHeadersEqualFold applies the EqualFold predicate on the "request_headers" field.
func RequestHeadersEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldRequestHeaders, v))
}

// RequestHeadersContainsFold applies the ContainsFold predicate on the "request_headers" field.
func RequestHeadersContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldRequestHeaders, v))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyContains applies the Contains predicate on the "request_body" field.
func RequestBodyContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldRequestBody, v))
}

// RequestBodyHasPrefix applies the HasPrefix predicate on the "request_body" field.
func RequestBodyHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldRequestBody, v))
}

// RequestBodyHasSuffix applies the HasSuffix predicate on the "request_body" field.
func RequestBodyHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldRequestBody, v))
}

// RequestBodyEqualFold applies the EqualFold predicate on the "request_body" field.
func RequestBodyEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldRequestBody, v))
}

// RequestBodyContainsFold applies the ContainsFold predicate on the "request_body" field.
func RequestBodyContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldRequestBody, v))
}

// ResponseHeadersEQ applies the EQ predicate on the "response_headers" field.
func ResponseHeadersEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseHeaders, v))
}

// ResponseHeadersNEQ applies the NEQ predicate on the "response_headers" field.
func ResponseHeadersNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldResponseHeaders, v))
}

// ResponseHeadersIn applies the In predicate on the "response_headers" field.
func ResponseHeadersIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldResponseHeaders, vs...))
}

// ResponseHeadersNotIn applies the NotIn predicate on the "response_headers" field.
func ResponseHeadersNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldResponseHeaders, vs...))
}

// ResponseHeadersGT applies the GT predicate on the "response_headers" field.
func ResponseHeadersGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldResponseHeaders, v))
}

// ResponseHeadersGTE applies the GTE predicate on the "response_headers" field.
func ResponseHeadersGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldResponseHeaders, v))
}

// ResponseHeadersLT applies the LT predicate on the "response_headers" field.
func ResponseHeadersLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldResponseHeaders, v))
}

// ResponseHeadersLTE applies the LTE predicate on the "response_headers" field.
func ResponseHeadersLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldResponseHeaders, v))
}

// ResponseHeadersContains applies the Contains predicate on the "response_headers" field.
func ResponseHeadersContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldResponseHeaders, v))
}

// ResponseHeadersHasPrefix applies the HasPrefix predicate on the "response_headers" field.
func ResponseHeadersHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldResponseHeaders, v))
}

// ResponseHeadersHasSuffix applies the HasSuffix predicate on the "response_headers" field.
func ResponseHeadersHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldResponseHeaders, v))
}

// ResponseHeadersEqualFold applies the EqualFold predicate on the "response_headers" field.
func ResponseHeadersEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldResponseHeaders, v))
}

// ResponseHeadersContainsFold applies the ContainsFold predicate on the "response_headers" field.
func ResponseHeadersContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldResponseHeaders, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyContains applies the Contains predicate on the "response_body" field.
func ResponseBodyContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldResponseBody, v))
}

// ResponseBodyHasPrefix applies the HasPrefix predicate on the "response_body" field.
func ResponseBodyHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldResponseBody, v))
}

// ResponseBodyHasSuffix applies the HasSuffix predicate on the "response_body" field.
func ResponseBodyHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldResponseBody, v))
}

// ResponseBodyEqualFold applies the EqualFold predicate on the "response_body" field.
func ResponseBodyEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldResponseBody, v))
}

// ResponseBodyContainsFold applies the ContainsFold predicate on the "response_body" field.
func ResponseBodyContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldResponseBody, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUsageLog applies the HasEdge predicate on the "usage_log" edge.
func HasUsageLog() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogWith applies the HasEdge predicate on the "usage_log" edge with a given conditions (other predicates).
func HasUsageLogWith(preds ...predicate.UsageLog) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(func(s *sql.Selector) {
		step := newUsageLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.NotPredicates(p))
}
