// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelogdetail"
)

// UsageLogDetailDelete is the builder for deleting a UsageLogDetail entity.
type UsageLogDetailDelete struct {
	config
	hooks    []Hook
	mutation *UsageLogDetailMutation
}

// Where appends a list predicates to the UsageLogDetailDelete builder.
func (_d *UsageLogDetailDelete) Where(ps ...predicate.UsageLogDetail) *UsageLogDetailDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UsageLogDetailDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UsageLogDetailDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UsageLogDetailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usagelogdetail.Table, sqlgraph.NewFieldSpec(usagelogdetail.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UsageLogDetailDeleteOne is the builder for deleting a single UsageLogDetail entity.
type UsageLogDetailDeleteOne struct {
	_d *UsageLogDetailDelete
}

// Where appends a list predicates to the UsageLogDetailDelete builder.
func (_d *UsageLogDetailDeleteOne) Where(ps ...predicate.UsageLogDetail) *UsageLogDetailDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UsageLogDetailDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usagelogdetail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UsageLogDetailDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
