// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/usagelogdetail"
)

// UsageLogDetailCreate is the builder for creating a UsageLogDetail entity.
type UsageLogDetailCreate struct {
	config
	mutation *UsageLogDetailMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *UsageLogDetailCreate) SetUsageLogID(v int64) *UsageLogDetailCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetDetailType sets the "detail_type" field.
func (_c *UsageLogDetailCreate) SetDetailType(v string) *UsageLogDetailCreate {
	_c.mutation.SetDetailType(v)
	return _c
}

// SetNillableDetailType sets the "detail_type" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableDetailType(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetDetailType(*v)
	}
	return _c
}

// SetRequestHeaders sets the "request_headers" field.
func (_c *UsageLogDetailCreate) SetRequestHeaders(v string) *UsageLogDetailCreate {
	_c.mutation.SetRequestHeaders(v)
	return _c
}

// SetNillableRequestHeaders sets the "request_headers" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableRequestHeaders(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetRequestHeaders(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *UsageLogDetailCreate) SetRequestBody(v string) *UsageLogDetailCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableRequestBody(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetRequestBody(*v)
	}
	return _c
}

// SetUpstreamRequestHeaders sets the "upstream_request_headers" field.
func (_c *UsageLogDetailCreate) SetUpstreamRequestHeaders(v string) *UsageLogDetailCreate {
	_c.mutation.SetUpstreamRequestHeaders(v)
	return _c
}

// SetNillableUpstreamRequestHeaders sets the "upstream_request_headers" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableUpstreamRequestHeaders(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetUpstreamRequestHeaders(*v)
	}
	return _c
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (_c *UsageLogDetailCreate) SetUpstreamRequestBody(v string) *UsageLogDetailCreate {
	_c.mutation.SetUpstreamRequestBody(v)
	return _c
}

// SetNillableUpstreamRequestBody sets the "upstream_request_body" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableUpstreamRequestBody(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetUpstreamRequestBody(*v)
	}
	return _c
}

// SetResponseHeaders sets the "response_headers" field.
func (_c *UsageLogDetailCreate) SetResponseHeaders(v string) *UsageLogDetailCreate {
	_c.mutation.SetResponseHeaders(v)
	return _c
}

// SetNillableResponseHeaders sets the "response_headers" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableResponseHeaders(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetResponseHeaders(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *UsageLogDetailCreate) SetResponseBody(v string) *UsageLogDetailCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableResponseBody(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetResponseBody(*v)
	}
	return _c
}

// SetUpstreamResponseHeaders sets the "upstream_response_headers" field.
func (_c *UsageLogDetailCreate) SetUpstreamResponseHeaders(v string) *UsageLogDetailCreate {
	_c.mutation.SetUpstreamResponseHeaders(v)
	return _c
}

// SetNillableUpstreamResponseHeaders sets the "upstream_response_headers" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableUpstreamResponseHeaders(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetUpstreamResponseHeaders(*v)
	}
	return _c
}

// SetUpstreamResponseBody sets the "upstream_response_body" field.
func (_c *UsageLogDetailCreate) SetUpstreamResponseBody(v string) *UsageLogDetailCreate {
	_c.mutation.SetUpstreamResponseBody(v)
	return _c
}

// SetNillableUpstreamResponseBody sets the "upstream_response_body" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableUpstreamResponseBody(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetUpstreamResponseBody(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageLogDetailCreate) SetCreatedAt(v time.Time) *UsageLogDetailCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableCreatedAt(v *time.Time) *UsageLogDetailCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_c *UsageLogDetailCreate) SetUsageLog(v *UsageLog) *UsageLogDetailCreate {
	return _c.SetUsageLogID(v.ID)
}

// Mutation returns the UsageLogDetailMutation object of the builder.
func (_c *UsageLogDetailCreate) Mutation() *UsageLogDetailMutation {
	return _c.mutation
}

// Save creates the UsageLogDetail in the database.
func (_c *UsageLogDetailCreate) Save(ctx context.Context) (*UsageLogDetail, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageLogDetailCreate) SaveX(ctx context.Context) *UsageLogDetail {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogDetailCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogDetailCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageLogDetailCreate) defaults() {
	if _, ok := _c.mutation.DetailType(); !ok {
		v := usagelogdetail.DefaultDetailType
		_c.mutation.SetDetailType(v)
	}
	if _, ok := _c.mutation.RequestHeaders(); !ok {
		v := usagelogdetail.DefaultRequestHeaders
		_c.mutation.SetRequestHeaders(v)
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		v := usagelogdetail.DefaultRequestBody
		_c.mutation.SetRequestBody(v)
	}
	if _, ok := _c.mutation.UpstreamRequestHeaders(); !ok {
		v := usagelogdetail.DefaultUpstreamRequestHeaders
		_c.mutation.SetUpstreamRequestHeaders(v)
	}
	if _, ok := _c.mutation.UpstreamRequestBody(); !ok {
		v := usagelogdetail.DefaultUpstreamRequestBody
		_c.mutation.SetUpstreamRequestBody(v)
	}
	if _, ok := _c.mutation.ResponseHeaders(); !ok {
		v := usagelogdetail.DefaultResponseHeaders
		_c.mutation.SetResponseHeaders(v)
	}
	if _, ok := _c.mutation.ResponseBody(); !ok {
		v := usagelogdetail.DefaultResponseBody
		_c.mutation.SetResponseBody(v)
	}
	if _, ok := _c.mutation.UpstreamResponseHeaders(); !ok {
		v := usagelogdetail.DefaultUpstreamResponseHeaders
		_c.mutation.SetUpstreamResponseHeaders(v)
	}
	if _, ok := _c.mutation.UpstreamResponseBody(); !ok {
		v := usagelogdetail.DefaultUpstreamResponseBody
		_c.mutation.SetUpstreamResponseBody(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagelogdetail.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageLogDetailCreate) check() error {
	if _, ok := _c.mutation.UsageLogID(); !ok {
		return &ValidationError{Name: "usage_log_id", err: errors.New(`ent: missing required field "UsageLogDetail.usage_log_id"`)}
	}
	if _, ok := _c.mutation.DetailType(); !ok {
		return &ValidationError{Name: "detail_type", err: errors.New(`ent: missing required field "UsageLogDetail.detail_type"`)}
	}
	if v, ok := _c.mutation.DetailType(); ok {
		if err := usagelogdetail.DetailTypeValidator(v); err != nil {
			return &ValidationError{Name: "detail_type", err: fmt.Errorf(`ent: validator failed for field "UsageLogDetail.detail_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestHeaders(); !ok {
		return &ValidationError{Name: "request_headers", err: errors.New(`ent: missing required field "UsageLogDetail.request_headers"`)}
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		return &ValidationError{Name: "request_body", err: errors.New(`ent: missing required field "UsageLogDetail.request_body"`)}
	}
	if _, ok := _c.mutation.UpstreamRequestHeaders(); !ok {
		return &ValidationError{Name: "upstream_request_headers", err: errors.New(`ent: missing required field "UsageLogDetail.upstream_request_headers"`)}
	}
	if _, ok := _c.mutation.UpstreamRequestBody(); !ok {
		return &ValidationError{Name: "upstream_request_body", err: errors.New(`ent: missing required field "UsageLogDetail.upstream_request_body"`)}
	}
	if _, ok := _c.mutation.ResponseHeaders(); !ok {
		return &ValidationError{Name: "response_headers", err: errors.New(`ent: missing required field "UsageLogDetail.response_headers"`)}
	}
	if _, ok := _c.mutation.ResponseBody(); !ok {
		return &ValidationError{Name: "response_body", err: errors.New(`ent: missing required field "UsageLogDetail.response_body"`)}
	}
	if _, ok := _c.mutation.UpstreamResponseHeaders(); !ok {
		return &ValidationError{Name: "upstream_response_headers", err: errors.New(`ent: missing required field "UsageLogDetail.upstream_response_headers"`)}
	}
	if _, ok := _c.mutation.UpstreamResponseBody(); !ok {
		return &ValidationError{Name: "upstream_response_body", err: errors.New(`ent: missing required field "UsageLogDetail.upstream_response_body"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLogDetail.created_at"`)}
	}
	if len(_c.mutation.UsageLogIDs()) == 0 {
		return &ValidationError{Name: "usage_log", err: errors.New(`ent: missing required edge "UsageLogDetail.usage_log"`)}
	}
	return nil
}

func (_c *UsageLogDetailCreate) sqlSave(ctx context.Context) (*UsageLogDetail, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageLogDetailCreate) createSpec() (*UsageLogDetail, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLogDetail{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagelogdetail.Table, sqlgraph.NewFieldSpec(usagelogdetail.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DetailType(); ok {
		_spec.SetField(usagelogdetail.FieldDetailType, field.TypeString, value)
		_node.DetailType = value
	}
	if value, ok := _c.mutation.RequestHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldRequestHeaders, field.TypeString, value)
		_node.RequestHeaders = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(usagelogdetail.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.UpstreamRequestHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamRequestHeaders, field.TypeString, value)
		_node.UpstreamRequestHeaders = value
	}
	if value, ok := _c.mutation.UpstreamRequestBody(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamRequestBody, field.TypeString, value)
		_node.UpstreamRequestBody = value
	}
	if value, ok := _c.mutation.ResponseHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldResponseHeaders, field.TypeString, value)
		_node.ResponseHeaders = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(usagelogdetail.FieldResponseBody, field.TypeString, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.UpstreamResponseHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamResponseHeaders, field.TypeString, value)
		_node.UpstreamResponseHeaders = value
	}
	if value, ok := _c.mutation.UpstreamResponseBody(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamResponseBody, field.TypeString, value)
		_node.UpstreamResponseBody = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagelogdetail.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsageLogID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLogDetail.Create().
//		SetUsageLogID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogDetailUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogDetailCreate) OnConflict(opts ...sql.ConflictOption) *UsageLogDetailUpsertOne {
	_c.conflict = opts
	return &UsageLogDetailUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogDetailCreate) OnConflictColumns(columns ...string) *UsageLogDetailUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogDetailUpsertOne{
		create: _c,
	}
}

type (
	// UsageLogDetailUpsertOne is the builder for "upsert"-ing
	//  one UsageLogDetail node.
	UsageLogDetailUpsertOne struct {
		create *UsageLogDetailCreate
	}

	// UsageLogDetailUpsert is the "OnConflict" setter.
	UsageLogDetailUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogDetailUpsert) SetUsageLogID(v int64) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateUsageLogID() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldUsageLogID)
	return u
}

// SetDetailType sets the "detail_type" field.
func (u *UsageLogDetailUpsert) SetDetailType(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldDetailType, v)
	return u
}

// UpdateDetailType sets the "detail_type" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateDetailType() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldDetailType)
	return u
}

// SetRequestHeaders sets the "request_headers" field.
func (u *UsageLogDetailUpsert) SetRequestHeaders(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldRequestHeaders, v)
	return u
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateRequestHeaders() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldRequestHeaders)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *UsageLogDetailUpsert) SetRequestBody(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateRequestBody() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldRequestBody)
	return u
}

// SetUpstreamRequestHeaders sets the "upstream_request_headers" field.
func (u *UsageLogDetailUpsert) SetUpstreamRequestHeaders(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldUpstreamRequestHeaders, v)
	return u
}

// UpdateUpstreamRequestHeaders sets the "upstream_request_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateUpstreamRequestHeaders() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldUpstreamRequestHeaders)
	return u
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (u *UsageLogDetailUpsert) SetUpstreamRequestBody(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldUpstreamRequestBody, v)
	return u
}

// UpdateUpstreamRequestBody sets the "upstream_request_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateUpstreamRequestBody() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldUpstreamRequestBody)
	return u
}

// SetResponseHeaders sets the "response_headers" field.
func (u *UsageLogDetailUpsert) SetResponseHeaders(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldResponseHeaders, v)
	return u
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateResponseHeaders() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldResponseHeaders)
	return u
}

// SetResponseBody sets the "response_body" field.
func (u *UsageLogDetailUpsert) SetResponseBody(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldResponseBody, v)
	return u
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateResponseBody() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldResponseBody)
	return u
}

// SetUpstreamResponseHeaders sets the "upstream_response_headers" field.
func (u *UsageLogDetailUpsert) SetUpstreamResponseHeaders(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldUpstreamResponseHeaders, v)
	return u
}

// UpdateUpstreamResponseHeaders sets the "upstream_response_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateUpstreamResponseHeaders() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldUpstreamResponseHeaders)
	return u
}

// SetUpstreamResponseBody sets the "upstream_response_body" field.
func (u *UsageLogDetailUpsert) SetUpstreamResponseBody(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldUpstreamResponseBody, v)
	return u
}

// UpdateUpstreamResponseBody sets the "upstream_response_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateUpstreamResponseBody() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldUpstreamResponseBody)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageLogDetailUpsertOne) UpdateNewValues() *UsageLogDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagelogdetail.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageLogDetailUpsertOne) Ignore() *UsageLogDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogDetailUpsertOne) DoNothing() *UsageLogDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogDetailCreate.OnConflict
// documentation for more info.
func (u *UsageLogDetailUpsertOne) Update(set func(*UsageLogDetailUpsert)) *UsageLogDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogDetailUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogDetailUpsertOne) SetUsageLogID(v int64) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateUsageLogID() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetDetailType sets the "detail_type" field.
func (u *UsageLogDetailUpsertOne) SetDetailType(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetDetailType(v)
	})
}

// UpdateDetailType sets the "detail_type" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateDetailType() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateDetailType()
	})
}

// SetRequestHeaders sets the "request_headers" field.
func (u *UsageLogDetailUpsertOne) SetRequestHeaders(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestHeaders(v)
	})
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateRequestHeaders() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestHeaders()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *UsageLogDetailUpsertOne) SetRequestBody(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateRequestBody() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestBody()
	})
}

// SetUpstreamRequestHeaders sets the "upstream_request_headers" field.
func (u *UsageLogDetailUpsertOne) SetUpstreamRequestHeaders(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpstreamRequestHeaders(v)
	})
}

// UpdateUpstreamRequestHeaders sets the "upstream_request_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateUpstreamRequestHeaders() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpstreamRequestHeaders()
	})
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (u *UsageLogDetailUpsertOne) SetUpstreamRequestBody(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpstreamRequestBody(v)
	})
}

// UpdateUpstreamRequestBody sets the "upstream_request_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateUpstreamRequestBody() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpstreamRequestBody()
	})
}

// SetResponseHeaders sets the "response_headers" field.
func (u *UsageLogDetailUpsertOne) SetResponseHeaders(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponseHeaders(v)
	})
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateResponseHeaders() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponseHeaders()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *UsageLogDetailUpsertOne) SetResponseBody(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateResponseBody() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponseBody()
	})
}

// SetUpstreamResponseHeaders sets the "upstream_response_headers" field.
func (u *UsageLogDetailUpsertOne) SetUpstreamResponseHeaders(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpstreamResponseHeaders(v)
	})
}

// UpdateUpstreamResponseHeaders sets the "upstream_response_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateUpstreamResponseHeaders() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpstreamResponseHeaders()
	})
}

// SetUpstreamResponseBody sets the "upstream_response_body" field.
func (u *UsageLogDetailUpsertOne) SetUpstreamResponseBody(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpstreamResponseBody(v)
	})
}

// UpdateUpstreamResponseBody sets the "upstream_response_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateUpstreamResponseBody() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpstreamResponseBody()
	})
}

// Exec executes the query.
func (u *UsageLogDetailUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogDetailCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogDetailUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageLogDetailUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageLogDetailUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageLogDetailCreateBulk is the builder for creating many UsageLogDetail entities in bulk.
type UsageLogDetailCreateBulk struct {
	config
	err      error
	builders []*UsageLogDetailCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageLogDetail entities in the database.
func (_c *UsageLogDetailCreateBulk) Save(ctx context.Context) ([]*UsageLogDetail, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageLogDetail, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogDetailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageLogDetailCreateBulk) SaveX(ctx context.Context) []*UsageLogDetail {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogDetailCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogDetailCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLogDetail.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogDetailUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogDetailCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageLogDetailUpsertBulk {
	_c.conflict = opts
	return &UsageLogDetailUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogDetailCreateBulk) OnConflictColumns(columns ...string) *UsageLogDetailUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogDetailUpsertBulk{
		create: _c,
	}
}

// UsageLogDetailUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageLogDetail nodes.
type UsageLogDetailUpsertBulk struct {
	create *UsageLogDetailCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageLogDetailUpsertBulk) UpdateNewValues() *UsageLogDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagelogdetail.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageLogDetailUpsertBulk) Ignore() *UsageLogDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogDetailUpsertBulk) DoNothing() *UsageLogDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogDetailCreateBulk.OnConflict
// documentation for more info.
func (u *UsageLogDetailUpsertBulk) Update(set func(*UsageLogDetailUpsert)) *UsageLogDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogDetailUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogDetailUpsertBulk) SetUsageLogID(v int64) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateUsageLogID() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetDetailType sets the "detail_type" field.
func (u *UsageLogDetailUpsertBulk) SetDetailType(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetDetailType(v)
	})
}

// UpdateDetailType sets the "detail_type" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateDetailType() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateDetailType()
	})
}

// SetRequestHeaders sets the "request_headers" field.
func (u *UsageLogDetailUpsertBulk) SetRequestHeaders(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestHeaders(v)
	})
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateRequestHeaders() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestHeaders()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *UsageLogDetailUpsertBulk) SetRequestBody(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateRequestBody() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestBody()
	})
}

// SetUpstreamRequestHeaders sets the "upstream_request_headers" field.
func (u *UsageLogDetailUpsertBulk) SetUpstreamRequestHeaders(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpstreamRequestHeaders(v)
	})
}

// UpdateUpstreamRequestHeaders sets the "upstream_request_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateUpstreamRequestHeaders() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpstreamRequestHeaders()
	})
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (u *UsageLogDetailUpsertBulk) SetUpstreamRequestBody(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpstreamRequestBody(v)
	})
}

// UpdateUpstreamRequestBody sets the "upstream_request_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateUpstreamRequestBody() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpstreamRequestBody()
	})
}

// SetResponseHeaders sets the "response_headers" field.
func (u *UsageLogDetailUpsertBulk) SetResponseHeaders(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponseHeaders(v)
	})
}

// UpdateResponseHeaders sets the "response_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateResponseHeaders() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponseHeaders()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *UsageLogDetailUpsertBulk) SetResponseBody(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateResponseBody() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponseBody()
	})
}

// SetUpstreamResponseHeaders sets the "upstream_response_headers" field.
func (u *UsageLogDetailUpsertBulk) SetUpstreamResponseHeaders(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpstreamResponseHeaders(v)
	})
}

// UpdateUpstreamResponseHeaders sets the "upstream_response_headers" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateUpstreamResponseHeaders() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpstreamResponseHeaders()
	})
}

// SetUpstreamResponseBody sets the "upstream_response_body" field.
func (u *UsageLogDetailUpsertBulk) SetUpstreamResponseBody(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpstreamResponseBody(v)
	})
}

// UpdateUpstreamResponseBody sets the "upstream_response_body" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateUpstreamResponseBody() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpstreamResponseBody()
	})
}

// Exec executes the query.
func (u *UsageLogDetailUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageLogDetailCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogDetailCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogDetailUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
