// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/usagelogdetail"
)

// UsageLogDetailUpdate is the builder for updating UsageLogDetail entities.
type UsageLogDetailUpdate struct {
	config
	hooks    []Hook
	mutation *UsageLogDetailMutation
}

// Where appends a list predicates to the UsageLogDetailUpdate builder.
func (_u *UsageLogDetailUpdate) Where(ps ...predicate.UsageLogDetail) *UsageLogDetailUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageLogDetailUpdate) SetUsageLogID(v int64) *UsageLogDetailUpdate {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableUsageLogID(v *int64) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *UsageLogDetailUpdate) SetRequestHeaders(v string) *UsageLogDetailUpdate {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// SetNillableRequestHeaders sets the "request_headers" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableRequestHeaders(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetRequestHeaders(*v)
	}
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *UsageLogDetailUpdate) SetRequestBody(v string) *UsageLogDetailUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableRequestBody(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// SetUpstreamRequestHeaders sets the "upstream_request_headers" field.
func (_u *UsageLogDetailUpdate) SetUpstreamRequestHeaders(v string) *UsageLogDetailUpdate {
	_u.mutation.SetUpstreamRequestHeaders(v)
	return _u
}

// SetNillableUpstreamRequestHeaders sets the "upstream_request_headers" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableUpstreamRequestHeaders(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetUpstreamRequestHeaders(*v)
	}
	return _u
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (_u *UsageLogDetailUpdate) SetUpstreamRequestBody(v string) *UsageLogDetailUpdate {
	_u.mutation.SetUpstreamRequestBody(v)
	return _u
}

// SetNillableUpstreamRequestBody sets the "upstream_request_body" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableUpstreamRequestBody(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetUpstreamRequestBody(*v)
	}
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *UsageLogDetailUpdate) SetResponseHeaders(v string) *UsageLogDetailUpdate {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// SetNillableResponseHeaders sets the "response_headers" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableResponseHeaders(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetResponseHeaders(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *UsageLogDetailUpdate) SetResponseBody(v string) *UsageLogDetailUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableResponseBody(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// SetUpstreamResponseHeaders sets the "upstream_response_headers" field.
func (_u *UsageLogDetailUpdate) SetUpstreamResponseHeaders(v string) *UsageLogDetailUpdate {
	_u.mutation.SetUpstreamResponseHeaders(v)
	return _u
}

// SetNillableUpstreamResponseHeaders sets the "upstream_response_headers" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableUpstreamResponseHeaders(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetUpstreamResponseHeaders(*v)
	}
	return _u
}

// SetUpstreamResponseBody sets the "upstream_response_body" field.
func (_u *UsageLogDetailUpdate) SetUpstreamResponseBody(v string) *UsageLogDetailUpdate {
	_u.mutation.SetUpstreamResponseBody(v)
	return _u
}

// SetNillableUpstreamResponseBody sets the "upstream_response_body" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableUpstreamResponseBody(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetUpstreamResponseBody(*v)
	}
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *UsageLogDetailUpdate) SetUsageLog(v *UsageLog) *UsageLogDetailUpdate {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the UsageLogDetailMutation object of the builder.
func (_u *UsageLogDetailUpdate) Mutation() *UsageLogDetailMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *UsageLogDetailUpdate) ClearUsageLog() *UsageLogDetailUpdate {
	_u.mutation.ClearUsageLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageLogDetailUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageLogDetailUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageLogDetailUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageLogDetailUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageLogDetailUpdate) check() error {
	if _u.mutation.UsageLogCleared() && len(_u.mutation.UsageLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageLogDetail.usage_log"`)
	}
	return nil
}

func (_u *UsageLogDetailUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagelogdetail.Table, usagelogdetail.Columns, sqlgraph.NewFieldSpec(usagelogdetail.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldRequestHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(usagelogdetail.FieldRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamRequestHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestBody(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldResponseHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(usagelogdetail.FieldResponseBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamResponseHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamResponseHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamResponseBody(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamResponseBody, field.TypeString, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagelogdetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageLogDetailUpdateOne is the builder for updating a single UsageLogDetail entity.
type UsageLogDetailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageLogDetailMutation
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageLogDetailUpdateOne) SetUsageLogID(v int64) *UsageLogDetailUpdateOne {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableUsageLogID(v *int64) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// SetRequestHeaders sets the "request_headers" field.
func (_u *UsageLogDetailUpdateOne) SetRequestHeaders(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetRequestHeaders(v)
	return _u
}

// SetNillableRequestHeaders sets the "request_headers" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableRequestHeaders(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetRequestHeaders(*v)
	}
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *UsageLogDetailUpdateOne) SetRequestBody(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableRequestBody(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// SetUpstreamRequestHeaders sets the "upstream_request_headers" field.
func (_u *UsageLogDetailUpdateOne) SetUpstreamRequestHeaders(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetUpstreamRequestHeaders(v)
	return _u
}

// SetNillableUpstreamRequestHeaders sets the "upstream_request_headers" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableUpstreamRequestHeaders(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestHeaders(*v)
	}
	return _u
}

// SetUpstreamRequestBody sets the "upstream_request_body" field.
func (_u *UsageLogDetailUpdateOne) SetUpstreamRequestBody(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetUpstreamRequestBody(v)
	return _u
}

// SetNillableUpstreamRequestBody sets the "upstream_request_body" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableUpstreamRequestBody(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestBody(*v)
	}
	return _u
}

// SetResponseHeaders sets the "response_headers" field.
func (_u *UsageLogDetailUpdateOne) SetResponseHeaders(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetResponseHeaders(v)
	return _u
}

// SetNillableResponseHeaders sets the "response_headers" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableResponseHeaders(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetResponseHeaders(*v)
	}
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *UsageLogDetailUpdateOne) SetResponseBody(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableResponseBody(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// SetUpstreamResponseHeaders sets the "upstream_response_headers" field.
func (_u *UsageLogDetailUpdateOne) SetUpstreamResponseHeaders(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetUpstreamResponseHeaders(v)
	return _u
}

// SetNillableUpstreamResponseHeaders sets the "upstream_response_headers" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableUpstreamResponseHeaders(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetUpstreamResponseHeaders(*v)
	}
	return _u
}

// SetUpstreamResponseBody sets the "upstream_response_body" field.
func (_u *UsageLogDetailUpdateOne) SetUpstreamResponseBody(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetUpstreamResponseBody(v)
	return _u
}

// SetNillableUpstreamResponseBody sets the "upstream_response_body" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableUpstreamResponseBody(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetUpstreamResponseBody(*v)
	}
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *UsageLogDetailUpdateOne) SetUsageLog(v *UsageLog) *UsageLogDetailUpdateOne {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the UsageLogDetailMutation object of the builder.
func (_u *UsageLogDetailUpdateOne) Mutation() *UsageLogDetailMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *UsageLogDetailUpdateOne) ClearUsageLog() *UsageLogDetailUpdateOne {
	_u.mutation.ClearUsageLog()
	return _u
}

// Where appends a list predicates to the UsageLogDetailUpdate builder.
func (_u *UsageLogDetailUpdateOne) Where(ps ...predicate.UsageLogDetail) *UsageLogDetailUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageLogDetailUpdateOne) Select(field string, fields ...string) *UsageLogDetailUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageLogDetail entity.
func (_u *UsageLogDetailUpdateOne) Save(ctx context.Context) (*UsageLogDetail, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageLogDetailUpdateOne) SaveX(ctx context.Context) *UsageLogDetail {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageLogDetailUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageLogDetailUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageLogDetailUpdateOne) check() error {
	if _u.mutation.UsageLogCleared() && len(_u.mutation.UsageLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageLogDetail.usage_log"`)
	}
	return nil
}

func (_u *UsageLogDetailUpdateOne) sqlSave(ctx context.Context) (_node *UsageLogDetail, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagelogdetail.Table, usagelogdetail.Columns, sqlgraph.NewFieldSpec(usagelogdetail.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageLogDetail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagelogdetail.FieldID)
		for _, f := range fields {
			if !usagelogdetail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagelogdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldRequestHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(usagelogdetail.FieldRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamRequestHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestBody(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamRequestBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldResponseHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(usagelogdetail.FieldResponseBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamResponseHeaders(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamResponseHeaders, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamResponseBody(); ok {
		_spec.SetField(usagelogdetail.FieldUpstreamResponseBody, field.TypeString, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageLogDetail{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagelogdetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
