// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/usagelogdetail"
)

// UsageLogDetail is the model entity for the UsageLogDetail schema.
type UsageLogDetail struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int64 `json:"usage_log_id,omitempty"`
	// DetailType holds the value of the "detail_type" field.
	DetailType string `json:"detail_type,omitempty"`
	// RequestHeaders holds the value of the "request_headers" field.
	RequestHeaders string `json:"request_headers,omitempty"`
	// RequestBody holds the value of the "request_body" field.
	RequestBody string `json:"request_body,omitempty"`
	// UpstreamRequestHeaders holds the value of the "upstream_request_headers" field.
	UpstreamRequestHeaders string `json:"upstream_request_headers,omitempty"`
	// UpstreamRequestBody holds the value of the "upstream_request_body" field.
	UpstreamRequestBody string `json:"upstream_request_body,omitempty"`
	// ResponseHeaders holds the value of the "response_headers" field.
	ResponseHeaders string `json:"response_headers,omitempty"`
	// ResponseBody holds the value of the "response_body" field.
	ResponseBody string `json:"response_body,omitempty"`
	// UpstreamResponseHeaders holds the value of the "upstream_response_headers" field.
	UpstreamResponseHeaders string `json:"upstream_response_headers,omitempty"`
	// UpstreamResponseBody holds the value of the "upstream_response_body" field.
	UpstreamResponseBody string `json:"upstream_response_body,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageLogDetailQuery when eager-loading is set.
	Edges        UsageLogDetailEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageLogDetailEdges holds the relations/edges for other nodes in the graph.
type UsageLogDetailEdges struct {
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogDetailEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageLogDetail) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagelogdetail.FieldID, usagelogdetail.FieldUsageLogID:
			values[i] = new(sql.NullInt64)
		case usagelogdetail.FieldDetailType, usagelogdetail.FieldRequestHeaders, usagelogdetail.FieldRequestBody, usagelogdetail.FieldUpstreamRequestHeaders, usagelogdetail.FieldUpstreamRequestBody, usagelogdetail.FieldResponseHeaders, usagelogdetail.FieldResponseBody, usagelogdetail.FieldUpstreamResponseHeaders, usagelogdetail.FieldUpstreamResponseBody:
			values[i] = new(sql.NullString)
		case usagelogdetail.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageLogDetail fields.
func (_m *UsageLogDetail) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagelogdetail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagelogdetail.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = value.Int64
			}
		case usagelogdetail.FieldDetailType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field detail_type", values[i])
			} else if value.Valid {
				_m.DetailType = value.String
			}
		case usagelogdetail.FieldRequestHeaders:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_headers", values[i])
			} else if value.Valid {
				_m.RequestHeaders = value.String
			}
		case usagelogdetail.FieldRequestBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body", values[i])
			} else if value.Valid {
				_m.RequestBody = value.String
			}
		case usagelogdetail.FieldUpstreamRequestHeaders:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_headers", values[i])
			} else if value.Valid {
				_m.UpstreamRequestHeaders = value.String
			}
		case usagelogdetail.FieldUpstreamRequestBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_body", values[i])
			} else if value.Valid {
				_m.UpstreamRequestBody = value.String
			}
		case usagelogdetail.FieldResponseHeaders:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_headers", values[i])
			} else if value.Valid {
				_m.ResponseHeaders = value.String
			}
		case usagelogdetail.FieldResponseBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_body", values[i])
			} else if value.Valid {
				_m.ResponseBody = value.String
			}
		case usagelogdetail.FieldUpstreamResponseHeaders:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_response_headers", values[i])
			} else if value.Valid {
				_m.UpstreamResponseHeaders = value.String
			}
		case usagelogdetail.FieldUpstreamResponseBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_response_body", values[i])
			} else if value.Valid {
				_m.UpstreamResponseBody = value.String
			}
		case usagelogdetail.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageLogDetail.
// This includes values selected through modifiers, order, etc.
func (_m *UsageLogDetail) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsageLog queries the "usage_log" edge of the UsageLogDetail entity.
func (_m *UsageLogDetail) QueryUsageLog() *UsageLogQuery {
	return NewUsageLogDetailClient(_m.config).QueryUsageLog(_m)
}

// Update returns a builder for updating this UsageLogDetail.
// Note that you need to call UsageLogDetail.Unwrap() before calling this method if this UsageLogDetail
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageLogDetail) Update() *UsageLogDetailUpdateOne {
	return NewUsageLogDetailClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageLogDetail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageLogDetail) Unwrap() *UsageLogDetail {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageLogDetail is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageLogDetail) String() string {
	var builder strings.Builder
	builder.WriteString("UsageLogDetail(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("detail_type=")
	builder.WriteString(_m.DetailType)
	builder.WriteString(", ")
	builder.WriteString("request_headers=")
	builder.WriteString(_m.RequestHeaders)
	builder.WriteString(", ")
	builder.WriteString("request_body=")
	builder.WriteString(_m.RequestBody)
	builder.WriteString(", ")
	builder.WriteString("upstream_request_headers=")
	builder.WriteString(_m.UpstreamRequestHeaders)
	builder.WriteString(", ")
	builder.WriteString("upstream_request_body=")
	builder.WriteString(_m.UpstreamRequestBody)
	builder.WriteString(", ")
	builder.WriteString("response_headers=")
	builder.WriteString(_m.ResponseHeaders)
	builder.WriteString(", ")
	builder.WriteString("response_body=")
	builder.WriteString(_m.ResponseBody)
	builder.WriteString(", ")
	builder.WriteString("upstream_response_headers=")
	builder.WriteString(_m.UpstreamResponseHeaders)
	builder.WriteString(", ")
	builder.WriteString("upstream_response_body=")
	builder.WriteString(_m.UpstreamResponseBody)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageLogDetails is a parsable slice of UsageLogDetail.
type UsageLogDetails []*UsageLogDetail
