// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userresourceoverride"
)

// UserResourceOverrideUpdate is the builder for updating UserResourceOverride entities.
type UserResourceOverrideUpdate struct {
	config
	hooks    []Hook
	mutation *UserResourceOverrideMutation
}

// Where appends a list predicates to the UserResourceOverrideUpdate builder.
func (_u *UserResourceOverrideUpdate) Where(ps ...predicate.UserResourceOverride) *UserResourceOverrideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserResourceOverrideUpdate) SetUserID(v int64) *UserResourceOverrideUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserResourceOverrideUpdate) SetNillableUserID(v *int64) *UserResourceOverrideUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *UserResourceOverrideUpdate) SetResourceType(v string) *UserResourceOverrideUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *UserResourceOverrideUpdate) SetNillableResourceType(v *string) *UserResourceOverrideUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UserResourceOverrideUpdate) SetResourceID(v int64) *UserResourceOverrideUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UserResourceOverrideUpdate) SetNillableResourceID(v *int64) *UserResourceOverrideUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *UserResourceOverrideUpdate) AddResourceID(v int64) *UserResourceOverrideUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetEffect sets the "effect" field.
func (_u *UserResourceOverrideUpdate) SetEffect(v string) *UserResourceOverrideUpdate {
	_u.mutation.SetEffect(v)
	return _u
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_u *UserResourceOverrideUpdate) SetNillableEffect(v *string) *UserResourceOverrideUpdate {
	if v != nil {
		_u.SetEffect(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserResourceOverrideUpdate) SetUser(v *User) *UserResourceOverrideUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserResourceOverrideMutation object of the builder.
func (_u *UserResourceOverrideUpdate) Mutation() *UserResourceOverrideMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserResourceOverrideUpdate) ClearUser() *UserResourceOverrideUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserResourceOverrideUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserResourceOverrideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserResourceOverrideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserResourceOverrideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserResourceOverrideUpdate) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := userresourceoverride.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "UserResourceOverride.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Effect(); ok {
		if err := userresourceoverride.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "UserResourceOverride.effect": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserResourceOverride.user"`)
	}
	return nil
}

func (_u *UserResourceOverrideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userresourceoverride.Table, userresourceoverride.Columns, sqlgraph.NewFieldSpec(userresourceoverride.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(userresourceoverride.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(userresourceoverride.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(userresourceoverride.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Effect(); ok {
		_spec.SetField(userresourceoverride.FieldEffect, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userresourceoverride.UserTable,
			Columns: []string{userresourceoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userresourceoverride.UserTable,
			Columns: []string{userresourceoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userresourceoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserResourceOverrideUpdateOne is the builder for updating a single UserResourceOverride entity.
type UserResourceOverrideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserResourceOverrideMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserResourceOverrideUpdateOne) SetUserID(v int64) *UserResourceOverrideUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserResourceOverrideUpdateOne) SetNillableUserID(v *int64) *UserResourceOverrideUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *UserResourceOverrideUpdateOne) SetResourceType(v string) *UserResourceOverrideUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *UserResourceOverrideUpdateOne) SetNillableResourceType(v *string) *UserResourceOverrideUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UserResourceOverrideUpdateOne) SetResourceID(v int64) *UserResourceOverrideUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UserResourceOverrideUpdateOne) SetNillableResourceID(v *int64) *UserResourceOverrideUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *UserResourceOverrideUpdateOne) AddResourceID(v int64) *UserResourceOverrideUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetEffect sets the "effect" field.
func (_u *UserResourceOverrideUpdateOne) SetEffect(v string) *UserResourceOverrideUpdateOne {
	_u.mutation.SetEffect(v)
	return _u
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_u *UserResourceOverrideUpdateOne) SetNillableEffect(v *string) *UserResourceOverrideUpdateOne {
	if v != nil {
		_u.SetEffect(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserResourceOverrideUpdateOne) SetUser(v *User) *UserResourceOverrideUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserResourceOverrideMutation object of the builder.
func (_u *UserResourceOverrideUpdateOne) Mutation() *UserResourceOverrideMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserResourceOverrideUpdateOne) ClearUser() *UserResourceOverrideUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserResourceOverrideUpdate builder.
func (_u *UserResourceOverrideUpdateOne) Where(ps ...predicate.UserResourceOverride) *UserResourceOverrideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserResourceOverrideUpdateOne) Select(field string, fields ...string) *UserResourceOverrideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserResourceOverride entity.
func (_u *UserResourceOverrideUpdateOne) Save(ctx context.Context) (*UserResourceOverride, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserResourceOverrideUpdateOne) SaveX(ctx context.Context) *UserResourceOverride {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserResourceOverrideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserResourceOverrideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserResourceOverrideUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := userresourceoverride.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "UserResourceOverride.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Effect(); ok {
		if err := userresourceoverride.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "UserResourceOverride.effect": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserResourceOverride.user"`)
	}
	return nil
}

func (_u *UserResourceOverrideUpdateOne) sqlSave(ctx context.Context) (_node *UserResourceOverride, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userresourceoverride.Table, userresourceoverride.Columns, sqlgraph.NewFieldSpec(userresourceoverride.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserResourceOverride.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userresourceoverride.FieldID)
		for _, f := range fields {
			if !userresourceoverride.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userresourceoverride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(userresourceoverride.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(userresourceoverride.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(userresourceoverride.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Effect(); ok {
		_spec.SetField(userresourceoverride.FieldEffect, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userresourceoverride.UserTable,
			Columns: []string{userresourceoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userresourceoverride.UserTable,
			Columns: []string{userresourceoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserResourceOverride{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userresourceoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
