// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userresourceoverride"
)

// UserResourceOverride is the model entity for the UserResourceOverride schema.
type UserResourceOverride struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID int64 `json:"resource_id,omitempty"`
	// Effect holds the value of the "effect" field.
	Effect string `json:"effect,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserResourceOverrideQuery when eager-loading is set.
	Edges        UserResourceOverrideEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserResourceOverrideEdges holds the relations/edges for other nodes in the graph.
type UserResourceOverrideEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserResourceOverrideEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserResourceOverride) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userresourceoverride.FieldID, userresourceoverride.FieldUserID, userresourceoverride.FieldResourceID:
			values[i] = new(sql.NullInt64)
		case userresourceoverride.FieldResourceType, userresourceoverride.FieldEffect:
			values[i] = new(sql.NullString)
		case userresourceoverride.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserResourceOverride fields.
func (_m *UserResourceOverride) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userresourceoverride.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userresourceoverride.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userresourceoverride.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case userresourceoverride.FieldResourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = value.Int64
			}
		case userresourceoverride.FieldEffect:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field effect", values[i])
			} else if value.Valid {
				_m.Effect = value.String
			}
		case userresourceoverride.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserResourceOverride.
// This includes values selected through modifiers, order, etc.
func (_m *UserResourceOverride) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserResourceOverride entity.
func (_m *UserResourceOverride) QueryUser() *UserQuery {
	return NewUserResourceOverrideClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserResourceOverride.
// Note that you need to call UserResourceOverride.Unwrap() before calling this method if this UserResourceOverride
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserResourceOverride) Update() *UserResourceOverrideUpdateOne {
	return NewUserResourceOverrideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserResourceOverride entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserResourceOverride) Unwrap() *UserResourceOverride {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserResourceOverride is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserResourceOverride) String() string {
	var builder strings.Builder
	builder.WriteString("UserResourceOverride(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceID))
	builder.WriteString(", ")
	builder.WriteString("effect=")
	builder.WriteString(_m.Effect)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserResourceOverrides is a parsable slice of UserResourceOverride.
type UserResourceOverrides []*UserResourceOverride
