// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userresourceoverride"
)

// UserResourceOverrideCreate is the builder for creating a UserResourceOverride entity.
type UserResourceOverrideCreate struct {
	config
	mutation *UserResourceOverrideMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserResourceOverrideCreate) SetUserID(v int64) *UserResourceOverrideCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *UserResourceOverrideCreate) SetResourceType(v string) *UserResourceOverrideCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *UserResourceOverrideCreate) SetResourceID(v int64) *UserResourceOverrideCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetEffect sets the "effect" field.
func (_c *UserResourceOverrideCreate) SetEffect(v string) *UserResourceOverrideCreate {
	_c.mutation.SetEffect(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserResourceOverrideCreate) SetCreatedAt(v time.Time) *UserResourceOverrideCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserResourceOverrideCreate) SetNillableCreatedAt(v *time.Time) *UserResourceOverrideCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserResourceOverrideCreate) SetUser(v *User) *UserResourceOverrideCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserResourceOverrideMutation object of the builder.
func (_c *UserResourceOverrideCreate) Mutation() *UserResourceOverrideMutation {
	return _c.mutation
}

// Save creates the UserResourceOverride in the database.
func (_c *UserResourceOverrideCreate) Save(ctx context.Context) (*UserResourceOverride, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserResourceOverrideCreate) SaveX(ctx context.Context) *UserResourceOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserResourceOverrideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserResourceOverrideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserResourceOverrideCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userresourceoverride.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserResourceOverrideCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserResourceOverride.user_id"`)}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "UserResourceOverride.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := userresourceoverride.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "UserResourceOverride.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "UserResourceOverride.resource_id"`)}
	}
	if _, ok := _c.mutation.Effect(); !ok {
		return &ValidationError{Name: "effect", err: errors.New(`ent: missing required field "UserResourceOverride.effect"`)}
	}
	if v, ok := _c.mutation.Effect(); ok {
		if err := userresourceoverride.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "UserResourceOverride.effect": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserResourceOverride.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserResourceOverride.user"`)}
	}
	return nil
}

func (_c *UserResourceOverrideCreate) sqlSave(ctx context.Context) (*UserResourceOverride, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserResourceOverrideCreate) createSpec() (*UserResourceOverride, *sqlgraph.CreateSpec) {
	var (
		_node = &UserResourceOverride{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userresourceoverride.Table, sqlgraph.NewFieldSpec(userresourceoverride.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(userresourceoverride.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(userresourceoverride.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Effect(); ok {
		_spec.SetField(userresourceoverride.FieldEffect, field.TypeString, value)
		_node.Effect = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userresourceoverride.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userresourceoverride.UserTable,
			Columns: []string{userresourceoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserResourceOverride.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserResourceOverrideUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserResourceOverrideCreate) OnConflict(opts ...sql.ConflictOption) *UserResourceOverrideUpsertOne {
	_c.conflict = opts
	return &UserResourceOverrideUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserResourceOverride.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserResourceOverrideCreate) OnConflictColumns(columns ...string) *UserResourceOverrideUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserResourceOverrideUpsertOne{
		create: _c,
	}
}

type (
	// UserResourceOverrideUpsertOne is the builder for "upsert"-ing
	//  one UserResourceOverride node.
	UserResourceOverrideUpsertOne struct {
		create *UserResourceOverrideCreate
	}

	// UserResourceOverrideUpsert is the "OnConflict" setter.
	UserResourceOverrideUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserResourceOverrideUpsert) SetUserID(v int64) *UserResourceOverrideUpsert {
	u.Set(userresourceoverride.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserResourceOverrideUpsert) UpdateUserID() *UserResourceOverrideUpsert {
	u.SetExcluded(userresourceoverride.FieldUserID)
	return u
}

// SetResourceType sets the "resource_type" field.
func (u *UserResourceOverrideUpsert) SetResourceType(v string) *UserResourceOverrideUpsert {
	u.Set(userresourceoverride.FieldResourceType, v)
	return u
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *UserResourceOverrideUpsert) UpdateResourceType() *UserResourceOverrideUpsert {
	u.SetExcluded(userresourceoverride.FieldResourceType)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *UserResourceOverrideUpsert) SetResourceID(v int64) *UserResourceOverrideUpsert {
	u.Set(userresourceoverride.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UserResourceOverrideUpsert) UpdateResourceID() *UserResourceOverrideUpsert {
	u.SetExcluded(userresourceoverride.FieldResourceID)
	return u
}

// AddResourceID adds v to the "resource_id" field.
func (u *UserResourceOverrideUpsert) AddResourceID(v int64) *UserResourceOverrideUpsert {
	u.Add(userresourceoverride.FieldResourceID, v)
	return u
}

// SetEffect sets the "effect" field.
func (u *UserResourceOverrideUpsert) SetEffect(v string) *UserResourceOverrideUpsert {
	u.Set(userresourceoverride.FieldEffect, v)
	return u
}

// UpdateEffect sets the "effect" field to the value that was provided on create.
func (u *UserResourceOverrideUpsert) UpdateEffect() *UserResourceOverrideUpsert {
	u.SetExcluded(userresourceoverride.FieldEffect)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserResourceOverride.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserResourceOverrideUpsertOne) UpdateNewValues() *UserResourceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userresourceoverride.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserResourceOverride.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserResourceOverrideUpsertOne) Ignore() *UserResourceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserResourceOverrideUpsertOne) DoNothing() *UserResourceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserResourceOverrideCreate.OnConflict
// documentation for more info.
func (u *UserResourceOverrideUpsertOne) Update(set func(*UserResourceOverrideUpsert)) *UserResourceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserResourceOverrideUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserResourceOverrideUpsertOne) SetUserID(v int64) *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserResourceOverrideUpsertOne) UpdateUserID() *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.UpdateUserID()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *UserResourceOverrideUpsertOne) SetResourceType(v string) *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *UserResourceOverrideUpsertOne) UpdateResourceType() *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *UserResourceOverrideUpsertOne) SetResourceID(v int64) *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *UserResourceOverrideUpsertOne) AddResourceID(v int64) *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UserResourceOverrideUpsertOne) UpdateResourceID() *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.UpdateResourceID()
	})
}

// SetEffect sets the "effect" field.
func (u *UserResourceOverrideUpsertOne) SetEffect(v string) *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.SetEffect(v)
	})
}

// UpdateEffect sets the "effect" field to the value that was provided on create.
func (u *UserResourceOverrideUpsertOne) UpdateEffect() *UserResourceOverrideUpsertOne {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.UpdateEffect()
	})
}

// Exec executes the query.
func (u *UserResourceOverrideUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserResourceOverrideCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserResourceOverrideUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserResourceOverrideUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserResourceOverrideUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserResourceOverrideCreateBulk is the builder for creating many UserResourceOverride entities in bulk.
type UserResourceOverrideCreateBulk struct {
	config
	err      error
	builders []*UserResourceOverrideCreate
	conflict []sql.ConflictOption
}

// Save creates the UserResourceOverride entities in the database.
func (_c *UserResourceOverrideCreateBulk) Save(ctx context.Context) ([]*UserResourceOverride, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserResourceOverride, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserResourceOverrideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserResourceOverrideCreateBulk) SaveX(ctx context.Context) []*UserResourceOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserResourceOverrideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserResourceOverrideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserResourceOverride.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserResourceOverrideUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserResourceOverrideCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserResourceOverrideUpsertBulk {
	_c.conflict = opts
	return &UserResourceOverrideUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserResourceOverride.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserResourceOverrideCreateBulk) OnConflictColumns(columns ...string) *UserResourceOverrideUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserResourceOverrideUpsertBulk{
		create: _c,
	}
}

// UserResourceOverrideUpsertBulk is the builder for "upsert"-ing
// a bulk of UserResourceOverride nodes.
type UserResourceOverrideUpsertBulk struct {
	create *UserResourceOverrideCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserResourceOverride.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserResourceOverrideUpsertBulk) UpdateNewValues() *UserResourceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userresourceoverride.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserResourceOverride.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserResourceOverrideUpsertBulk) Ignore() *UserResourceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserResourceOverrideUpsertBulk) DoNothing() *UserResourceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserResourceOverrideCreateBulk.OnConflict
// documentation for more info.
func (u *UserResourceOverrideUpsertBulk) Update(set func(*UserResourceOverrideUpsert)) *UserResourceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserResourceOverrideUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserResourceOverrideUpsertBulk) SetUserID(v int64) *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserResourceOverrideUpsertBulk) UpdateUserID() *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.UpdateUserID()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *UserResourceOverrideUpsertBulk) SetResourceType(v string) *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *UserResourceOverrideUpsertBulk) UpdateResourceType() *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *UserResourceOverrideUpsertBulk) SetResourceID(v int64) *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *UserResourceOverrideUpsertBulk) AddResourceID(v int64) *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UserResourceOverrideUpsertBulk) UpdateResourceID() *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.UpdateResourceID()
	})
}

// SetEffect sets the "effect" field.
func (u *UserResourceOverrideUpsertBulk) SetEffect(v string) *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.SetEffect(v)
	})
}

// UpdateEffect sets the "effect" field to the value that was provided on create.
func (u *UserResourceOverrideUpsertBulk) UpdateEffect() *UserResourceOverrideUpsertBulk {
	return u.Update(func(s *UserResourceOverrideUpsert) {
		s.UpdateEffect()
	})
}

// Exec executes the query.
func (u *UserResourceOverrideUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserResourceOverrideCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserResourceOverrideCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserResourceOverrideUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
