// Code generated by ent, DO NOT EDIT.

package userresourceoverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldUserID, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldResourceType, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldResourceID, v))
}

// Effect applies equality check predicate on the "effect" field. It's identical to EffectEQ.
func Effect(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldEffect, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNotIn(FieldUserID, vs...))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldContainsFold(FieldResourceType, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v int64) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLTE(FieldResourceID, v))
}

// EffectEQ applies the EQ predicate on the "effect" field.
func EffectEQ(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldEffect, v))
}

// EffectNEQ applies the NEQ predicate on the "effect" field.
func EffectNEQ(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNEQ(FieldEffect, v))
}

// EffectIn applies the In predicate on the "effect" field.
func EffectIn(vs ...string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldIn(FieldEffect, vs...))
}

// EffectNotIn applies the NotIn predicate on the "effect" field.
func EffectNotIn(vs ...string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNotIn(FieldEffect, vs...))
}

// EffectGT applies the GT predicate on the "effect" field.
func EffectGT(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGT(FieldEffect, v))
}

// EffectGTE applies the GTE predicate on the "effect" field.
func EffectGTE(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGTE(FieldEffect, v))
}

// EffectLT applies the LT predicate on the "effect" field.
func EffectLT(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLT(FieldEffect, v))
}

// EffectLTE applies the LTE predicate on the "effect" field.
func EffectLTE(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLTE(FieldEffect, v))
}

// EffectContains applies the Contains predicate on the "effect" field.
func EffectContains(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldContains(FieldEffect, v))
}

// EffectHasPrefix applies the HasPrefix predicate on the "effect" field.
func EffectHasPrefix(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldHasPrefix(FieldEffect, v))
}

// EffectHasSuffix applies the HasSuffix predicate on the "effect" field.
func EffectHasSuffix(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldHasSuffix(FieldEffect, v))
}

// EffectEqualFold applies the EqualFold predicate on the "effect" field.
func EffectEqualFold(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEqualFold(FieldEffect, v))
}

// EffectContainsFold applies the ContainsFold predicate on the "effect" field.
func EffectContainsFold(v string) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldContainsFold(FieldEffect, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserResourceOverride {
	return predicate.UserResourceOverride(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserResourceOverride) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserResourceOverride) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserResourceOverride) predicate.UserResourceOverride {
	return predicate.UserResourceOverride(sql.NotPredicates(p))
}
